const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { JSDOM, VirtualConsole } = require('jsdom');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)];
scripts.forEach((m, i) => new vm.Script(m[1], { filename: `inline-${i}.js` }));
const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', error => errors.push(error.message));
const dom = new JSDOM(html, {
  url: 'https://example.test/unmyeong/', runScripts: 'dangerously',
  pretendToBeVisual: true, virtualConsole,
  beforeParse(w) {
    w.TextEncoder = TextEncoder; w.TextDecoder = TextDecoder;
    w.URL.createObjectURL = () => 'blob:test'; w.URL.revokeObjectURL = () => {};
    w.localStorage.setItem('ug_welcomed', 'true');
    w.print = () => {};
  }
});
const w = dom.window;
const run = code => w.eval(code);
const fixture = (overrides = {}) => ({id:'regression',name:'검토용',gender:'M',cal:'S',y:1990,mo:1,d:1,h:9,min:30,noTime:false,memo:'비공개 메모 검증',...overrides});
const use = record => {
  w.testRecord = record;
  run('people=[window.testRecord];currentId=window.testRecord.id;selLuck={};selYear={};settings.correction=true;settings.lateNight=false;view="home";render();');
};

(async () => {
  await new Promise(resolve => setTimeout(resolve, 30));
  assert.equal(w.SajuEngine !== undefined, true);
  use(fixture());
  assert.equal(run('computed(people[0]).yearNum'), 1989, '입춘 연주는 유지');
  assert.equal(run('computed(people[0]).solar.y'), 1990, '실제 출생연도 분리');
  run('goYear(2026)');
  assert.equal(w.document.querySelector('.badge.eq').textContent, '37세');
  assert.equal(run('luckAt(computed(people[0]),2026).age'), 37);
  assert.equal(run('luckAt(computed(people[0]),2026).luck.age'), 28, '대운 전환을 1년 앞당기지 않음');
  assert.match(run('renderMemoView()'), /2026년 37세/);
  assert.match(run('buildAiPrompt(people[0],2026)'), /조회 2026년 37세/);
  run('goYear(2027)');
  assert.equal(run('luckAt(computed(people[0]),2027).luck.age'), 38);
  assert.equal(w.document.querySelector('.badge.eq').textContent, '38세');
  run('window._nowPid=currentId;window._nowDT={y:2027,mo:1,d:1,h:12,min:0};renderNow();');
  assert.match(w.document.querySelector('#nowBody .pillars').textContent,/38세~/);

  for (const rec of [fixture({y:1983,mo:12,d:12,h:9,min:0}),fixture({y:1990,mo:2,d:5}),fixture({cal:'L',y:1989,mo:12,d:5}),fixture({y:1990,h:0,min:10}),fixture({noTime:true,h:null,min:null})]) {
    use(rec); run('goYear(2027)');
    const age = run('2027-computed(people[0]).solar.y+1');
    assert.equal(w.document.querySelector('.badge.eq').textContent, `${age}세`);
    assert.equal(run('luckAt(computed(people[0]),2027).age'), age);
    assert.match(run('renderMemoView()'), new RegExp(`2027년 ${age}세`));
    const years = JSON.parse(run('JSON.stringify(E.yearlyLuck(computed(people[0]).solar.y,computed(people[0]).luck[0].age))'));
    assert.equal(years[0].year - run('computed(people[0]).solar.y') + 1, years[0].age);
  }
  use(fixture({y:1983,mo:12,d:12,h:9,min:0}));
  assert.equal(run('E.STEMS[computed(people[0]).pillars.hour.stem]+E.BRANCHES[computed(people[0]).pillars.hour.branch]'), '戊辰');
  run('settings.correction=false');
  assert.equal(run('E.STEMS[computed(people[0]).pillars.hour.stem]+E.BRANCHES[computed(people[0]).pillars.hour.branch]'), '己巳');
  run('settings.correction=true;goYear(2027);showCalculationBasis()');
  assert.match(w.document.querySelector('#infoBody').textContent, /08:30/);

  for(let month=1; month<=12; month++) {
    const period=JSON.parse(run(`JSON.stringify(monthPeriod(2027,${month}))`));
    assert.ok(period.start && period.end);
    const start=Date.UTC(period.start.year,period.start.m-1,period.start.d,period.start.h-9,period.start.min);
    const end=Date.UTC(period.end.year,period.end.m-1,period.end.d,period.end.h-9,period.end.min);
    assert.equal(run(`isCurrentMonthPeriod(2027,${month},new Date(${start}))`),true);
    assert.equal(run(`isCurrentMonthPeriod(2027,${month},new Date(${end}))`),false);
    assert.equal(run(`isCurrentMonthPeriod(2027,${month},new Date(${start-1}))`),false);
  }
  assert.equal(run('monthPeriod(2027,12).end.year'),2028);
  run('closeInfo();render();');
  w.document.querySelector('[aria-label="2027년 8월 상세"]').click();
  assert.match(w.document.querySelector('#infoBody').textContent,/戊申/);
  assert.match(w.document.querySelector('#infoBody').textContent,/KST/);
  run('closeInfo();setChartMode("simple")');
  assert.ok(w.document.querySelector('.card-pillars:not(.is-simple)'));
  assert.equal(JSON.parse(w.localStorage.getItem('ug_settings')).chartMode,'simple');

  run('showReportOptions()');
  assert.equal(w.document.querySelector('#report-memo').checked,false);
  assert.equal(w.document.querySelector('#report-reading').checked,false);
  const publicReport=run('reportHtml(people[0],2027,{luck:true,private:true})');
  assert.doesNotMatch(publicReport,/검토용|1983|09:00|08:30|비공개 메모 검증/);
  assert.match(publicReport,/2027年|2027년/);
  assert.match(publicReport,/2028\.01/);
  assert.match(run('reportHtml(people[0],2027,{memo:true})'),/비공개 메모 검증/);
  run('people[0].aiReadings={2027:{text:"저장된 풀이",at:Date.now(),basis:calculationSummary(people[0],computed(people[0]))}}');
  assert.doesNotMatch(run('reportHtml(people[0],2027,{private:true,reading:true})'),/1983\.12\.12|09:00|08:30/);
  run('printReport()');
  assert.ok(w.document.querySelector('#print-report'));
  assert.doesNotMatch(w.document.querySelector('#print-report').textContent,/비공개 메모 검증/);
  w.dispatchEvent(new w.Event('afterprint'));
  assert.equal(w.document.querySelector('#print-report'),null);

  // 공유 링크는 열기만 해서는 사람을 저장하지 않는다.
  run('window.testLink=buildPersonLink({...people[0],name:"공유검증"});');
  w.location.hash = new URL(w.testLink).hash;
  const before=run('people.length');
  assert.equal(run('checkIncomingLink()'),true);
  assert.equal(run('people.length'),before);
  assert.match(w.document.querySelector('#infoBody').textContent,/내 목록에 추가/);

  // 공유 취소·다운로드 준비 실패를 백업 성공으로 표시하지 않는다.
  run('store.set("ug_lastFileBackup",0);');
  Object.defineProperty(w.navigator,'canShare',{value:()=>true,configurable:true});
  Object.defineProperty(w.navigator,'share',{value:async()=>{throw new w.DOMException('취소','AbortError');},configurable:true});
  await run('shareExport()');
  assert.equal(run('store.get("ug_lastFileBackup",0)'),0);
  w.URL.createObjectURL = () => {throw new Error('저장 실패');};
  await run('exportData()');
  assert.equal(run('store.get("ug_lastFileBackup",0)'),0);
  assert.match(run('buildAiPrompt(people[0],2027)'),/12월/);
  assert.match(run('buildAiPrompt(people[0],2027)'),/원국 네 기둥/);

  // 전문가 전환은 명식 데이터와 조회 중인 연도·대운을 그대로 사용한다.
  run('closeInfo();goYear(2027)');
  const peopleBeforeMode=run('JSON.stringify(people)');
  const selectionBeforeMode=run('JSON.stringify([selLuck,selYear])');
  run('setDisplayMode("expert")');
  assert.equal(run('JSON.stringify(people)'),peopleBeforeMode);
  assert.equal(run('JSON.stringify([selLuck,selYear])'),selectionBeforeMode);
  assert.equal(w.document.querySelector('#main').dataset.mode,'standard');
  assert.equal(JSON.parse(w.localStorage.getItem('ug_settings')).displayMode,'standard');
  assert.equal(new URL(w.location.href).searchParams.get('mode'),'standard');
  assert.ok(w.document.querySelector('.card-pillars'));
  const expertStems=[...w.document.querySelectorAll('.card-pillars .pcol')].map(el=>el.querySelectorAll('.tile')[0].childNodes[0].textContent);
  const expertBranches=[...w.document.querySelectorAll('.card-pillars .pcol')].map(el=>el.querySelectorAll('.tile')[1].childNodes[0].textContent);
  assert.deepEqual(expertStems.slice(2),['丁','己','戊','甲','甲','癸']);
  assert.deepEqual(expertBranches.slice(2),['未','未','辰','戌','子','亥']);
  assert.equal(w.document.querySelectorAll('.card-pillars .tile').length,16);
  assert.equal(w.document.querySelector('.x-chart'),null);
  run('people.push({...people[0],id:"second",name:"홍길동",tag:"상담 고객"});render();showExpertPeople()');
  assert.equal(w.document.querySelectorAll('.x-person-result').length,2);
  run('filterExpertPeople("홍길동")');
  assert.equal(w.document.querySelectorAll('.x-person-result').length,1);
  assert.equal(w.document.querySelector('.x-person-result b').textContent,'홍길동');
  run('people=people.filter(p=>p.id!=="second");closeInfo();render()');
  w.document.querySelector('[aria-label="2027년 8월 상세"]').click();
  assert.match(w.document.querySelector('#infoBody').textContent,/戊申/);
  run('closeInfo()');
  assert.equal(w.document.querySelector('[aria-label="다음 연도"]'),null);
  run('goYear(2028)');
  assert.equal(run('window._homeYearShown'),2028);
  run('pickLuck(5)');
  assert.equal(run('window._homeYearShown'),2033);
  run('goYear(2027);showReportOptions();printReport()');
  assert.match(w.document.querySelector('#print-report').textContent,/2027년 명식 보고서/);
  assert.match(w.document.querySelector('#print-report').textContent,/戊辰/);
  run('closeInfo();setDisplayMode("standard")');
  assert.ok(w.document.querySelector('.card-pillars:not(.is-simple)'));
  assert.equal(w.document.querySelector('#main').dataset.mode,'standard');
  assert.equal(run('JSON.stringify(people)'),peopleBeforeMode);
  assert.equal(w.document.querySelector('.badge.eq').textContent,'45세');
  use(fixture({noTime:true,h:null,min:null}));
  run('setDisplayMode("expert")');
  assert.match(w.document.querySelector('.card-pillars').textContent,/모름/);
  run('homeDepth[currentId]=0;render()');
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol').length,8);
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol .tile.empty').length,2);
  assert.equal(w.document.querySelectorAll('.home-secondary .strip').length,1);
  run('pickLuck(3)');
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol').length,8);
  assert.equal(w.document.querySelectorAll('.home-secondary .strip').length,2);
  run('pickYear(1)');
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol').length,8);
  assert.equal(w.document.querySelectorAll('.home-secondary .strip').length,3);
  w.document.querySelector('.person-name').click();
  assert.equal(w.document.querySelectorAll('.home-secondary .strip').length,1);
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol').length,8);
  assert.equal(w.document.querySelector('#rd-pane-natal'),null);
  assert.equal(w.document.querySelector('#rd-pane-year'),null);
  assert.ok(w.document.querySelector('#rd-pane-ai'));
  assert.ok(w.document.querySelector('#chatgpt-open-btn'));
  const opened=[];let copiedPrompt='';
  w.document.execCommand=()=>{copiedPrompt=w.document.activeElement.value;return true;};
  w.open=(...args)=>{opened.push(args);return null;};
  await run('openChatGptReading(currentId,2027)');
  assert.equal(opened.length,1);
  assert.equal(opened[0][0],'https://chatgpt.com/');
  assert.equal(opened[0][2],'noopener,noreferrer');
  assert.match(copiedPrompt,/2027/);
  assert.ok(!copiedPrompt.includes('검토용'));
  assert.ok(!copiedPrompt.includes('비공개 메모 검증'));
  assert.match(w.document.querySelector('#chatgpt-copy-status').textContent,/복사했습니다/);
  Object.defineProperty(w.navigator,'clipboard',{configurable:true,value:{writeText:async value=>{copiedPrompt=value;}}});
  w.document.execCommand=()=>{throw Error('modern path must not use legacy copy');};
  await run('openChatGptReading(currentId,2027)');
  assert.equal(opened.length,2);
  assert.match(copiedPrompt,/2027/);
  delete w.navigator.clipboard;
  w.document.execCommand=()=>false;
  await run('openChatGptReading(currentId,2027)');
  assert.equal(opened.length,2,'복사 실패 시 외부 탭을 열지 않는다');
  assert.match(w.document.querySelector('#chatgpt-copy-status').textContent,/하지 못했습니다/);
  assert.ok(w.document.querySelector('#chatgpt-transfer-text').value.length>100);
  run('closeInfo()');
  const sentBasis=run('window._chatgptTransferCtx.basisKey');
  run('settings.correction=!settings.correction;showPastedAiReading(currentId,2027,true)');
  w.document.querySelector('#ai-paste-text').value='저장 검증 <img src=x onerror="alert(1)">';
  await run('savePastedAiReading()');
  assert.equal(run('people[0].aiReadings[2027].basisKey'),sentBasis);
  assert.match(w.document.querySelector('#rd-pane-ai').textContent,/계산 조건이 현재와 다릅니다/);
  assert.equal(w.document.querySelector('#rd-pane-ai img'),null);
  assert.equal(JSON.parse(w.localStorage.getItem('ug_people'))[0].aiReadings[2027].source,'chatgpt-paste');
  run('showPastedAiReading(currentId,2028)');
  w.document.querySelector('#ai-paste-text').value='2028년 저장 풀이';
  await run('savePastedAiReading()');
  assert.equal(run('people[0].aiReadings[2028].text'),'2028년 저장 풀이');
  assert.ok(run('people[0].aiReadings[2027].text').startsWith('저장 검증'));
  run('showPastedAiReading(currentId,2028)');
  w.document.querySelector('#ai-paste-text').value='  ';
  await run('savePastedAiReading()');
  assert.equal(run('people[0].aiReadings[2028].text'),'2028년 저장 풀이');
  run('closeInfo();goYear(2028)');
  assert.match(w.document.querySelector('#rd-pane-ai').textContent,/2028년 저장 풀이/);
  assert.throws(()=>run('aiServerUrl("http://unsafe.test")'));

  // 명식 옆 자동 저장: 같은 해 복수 기록, 강의, 일반 메모를 서로 덮어쓰지 않는다.
  use(fixture({yearMemos:[{year:2026,text:'이전 상담'},{id:'second',year:2026,text:'두 번째 상담'}]}));
  run('openNotebook("year",2026)');
  assert.equal(w.document.querySelector('#nb-editor').value,'두 번째 상담');
  assert.equal(w.document.querySelectorAll('.card-pillars .pcol').length,8);
  assert.ok(w.document.querySelector('#main.with-notebook'));
  assert.equal(run('people[0].yearMemos.length'),2,'여는 것만으로 빈 기록을 만들지 않는다');
  const writeNote=text=>{const el=w.document.querySelector('#nb-editor');el.value=text;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
  writeNote('2026년 수정\n명식을 보며 기록');
  run('notebookYear(2027)');
  assert.equal(w.document.querySelector('#nb-editor').value,'');
  assert.equal(w.document.querySelector('#nb-editor').getAttribute('aria-label'),'2027년 메모');
  writeNote('2027년 확인할 일');
  run('notebookYear(2026)');
  assert.match(w.document.querySelector('#nb-editor').value,/2026년 수정/);
  assert.equal(run('people[0].yearMemos[0].text'),'이전 상담');
  run('notebookChoose(people[0].yearMemos[0].id)');
  assert.equal(w.document.querySelector('#nb-editor').value,'이전 상담');
  run('notebookNew()');
  assert.equal(run('people[0].yearMemos.length'),3,'새 메모 버튼만 누르면 빈 기록이 저장되지 않는다');
  writeNote('새로운 상담 기록');
  assert.equal(run('people[0].yearMemos.length'),4);
  run('notebookMode("study");notebookTitle("십성 수업 <img src=x>")');
  writeNote('수업 중 정리\n1. 원국과 운을 구분');
  run('notebookMode("general")');
  assert.equal(w.document.querySelector('#nb-editor').value,'비공개 메모 검증');
  run('notebookMode("study")');
  assert.match(w.document.querySelector('#nb-editor').value,/수업 중 정리/);
  assert.equal(run('people[0].studyNotes.length'),1);
  run('notebookNew()');writeNote('두 번째 강의');
  assert.equal(run('people[0].studyNotes.length'),2);
  const preserved=JSON.parse(run('JSON.stringify(people[0])'));
  w.secondPerson=fixture({id:'second-person',name:'다른 명식',memo:'다른 일반 기록'});
  run('people.push(window.secondPerson);openPerson("second-person");notebookMode("year");notebookYear(2027)');
  writeNote('다른 사람의 2027');
  await new Promise(resolve=>setTimeout(resolve,600));
  const storedNotes=JSON.parse(w.localStorage.getItem('ug_people'));
  assert.deepEqual(storedNotes[0],preserved,'사람을 바꿔도 앞사람의 지연 저장 내용이 섞이지 않는다');
  assert.equal(storedNotes[1].yearMemos[0].text,'다른 사람의 2027');
  assert.match(w.document.querySelector('#nb-save-status').textContent,/저장됨/);
  run('openPerson("regression");go("memo")');
  assert.equal(w.document.querySelectorAll('.memo-review-item').length,2);
  assert.equal(w.document.querySelector('.memo-review-item img'),null,'강의 제목을 HTML로 실행하지 않는다');
  assert.ok(w.document.querySelector('.memo-years').open);
  const noteBackup=await run('buildPayload()');
  assert.equal(noteBackup.people[0].studyNotes[0].text,'수업 중 정리\n1. 원국과 운을 구분');
  // 대운 시작 전 / 표시된 열 대운 이후도 입력한 연도를 그대로 표시한다.
  run('openNotebook("year",1990)');
  assert.equal(run('window._homeYearShown'),1990);
  assert.equal(w.document.querySelector('#nb-editor').getAttribute('aria-label'),'1990년 메모');
  run('notebookYear(2099)');
  assert.equal(run('window._homeYearShown'),2099);
  assert.match(w.document.querySelector('.card-pillars').textContent,/2099/);
  run('notebookYear(2026);pickLuck(4);pickYear(3)');
  assert.equal(w.document.querySelector('.nb-year').value,String(run('window._homeYearShown')));
  run('notebookMode("study");notebookChoose(people[0].studyNotes[0].id)');
  const oldSaver=run('savePeople');w.failingSaver=()=>Promise.resolve(false);run('savePeople=window.failingSaver');
  writeNote('저장 실패에도 편집 내용 보존');
  await run('flushNotebook()');
  assert.match(w.document.querySelector('#nb-save-status').textContent,/저장 실패/);
  assert.equal(w.document.querySelector('#nb-editor').value,'저장 실패에도 편집 내용 보존');
  w.originalSaver=oldSaver;run('savePeople=window.originalSaver');await run('flushNotebook()');
  assert.match(w.document.querySelector('#nb-save-status').textContent,/저장됨/);
  run('toggleNotebook(false)');
  assert.equal(w.document.querySelector('#nb-editor'),null);
  assert.ok(w.document.querySelector('.notebook-launch'));

  use(fixture({recs:[{ts:123,dur:5,transcript:'확인한 음성 기록'}]}));
  const initialMemo=run('people[0].memo');
  run('appendTranscript(currentId,123);appendTranscript(currentId,123)');
  assert.equal(run('people[0].memo.match(/확인한 음성 기록/g).length'),1);
  assert.ok(run('people[0].memo').startsWith(initialMemo));
  const memoHTML=run('renderMemoView()');
  assert.ok(memoHTML.indexOf('memo-heading">메모')<memoHTML.indexOf('음성 기록'));
  assert.ok(memoHTML.includes('memo-years'));
  run('settings.aiServerUrl="https://server.test";window._aiAccessToken="test-access"');
  w.fetch=async()=>({ok:true,json:async()=>({text:'모의 GPT 풀이',model:'test-model'})});
  await run('aiGenerate(currentId,2027)');
  assert.equal(run('people[0].aiReadings[2027].text'),'모의 GPT 풀이');
  w.fetch=async()=>({ok:false,json:async()=>({error:'연결 실패'})});
  await run('aiGenerate(currentId,2027)');
  assert.equal(run('people[0].aiReadings[2027].text'),'모의 GPT 풀이');
  let stoppedTracks=0,speechStarts=0;
  w.SpeechRecognition=function(){speechStarts++;};
  Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>stoppedTracks++}]})},configurable:true});
  w.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){this.state='inactive';this.mimeType='audio/webm';}start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new w.Blob(['audio'])});this.onstop();}};
  run('idbSet=async()=>true');
  await run('startRec()');await run('stopRec()');
  assert.equal(speechStarts,0);assert.equal(stoppedTracks,1);
  assert.equal(run('people[0].recs.length'),2);
  run('idbSet=async()=>false');
  await run('startRec()');await run('stopRec()');
  assert.ok(run('window._unsavedRecording.blob.size')>0);
  assert.equal(run('people[0].recs.length'),2);
  run('window._unsavedRecording=null');
  run('people=[];currentId=null;render()');
  assert.match(w.document.querySelector('#main').textContent,/첫 명식 등록/);
  assert.deepEqual(errors,[]);
  console.log('PASS: existing regression suite; expert/standard switch preserves people and selection, six pillars match, year/luck/month controls, PDF, unknown time and empty state');
  w.close();
})().catch(error=>{console.error(error);w.close();process.exitCode=1;});
