// Calendar-only 24 solar terms. The birth engine retains its original term table.
const fs=require('node:fs');
const A=require('astronomy-engine');
const table={};
for(let y=1890;y<=2101;y++){
 table[y]=Array.from({length:24},(_,i)=>{
  const start=new Date(Date.UTC(y,Math.floor(i/2),i%2?15:1));
  const result=A.SearchSunLongitude((285+15*i)%360,start,15);
  if(!result)throw Error(`${y}:${i}`);
  return Math.round(result.date.getTime()/60000);
 });
}
fs.writeFileSync('solar-terms.js','// Astronomy Engine 2.1.19 (MIT), generated by scripts/generate-terms.cjs. Calendar display only.\nwindow.CALENDAR_TERMS='+JSON.stringify(table)+';\n');
